image: maven:3.6.3
pipelines:
  default:
    - step:
        name: Build and Push Wavenet Repository
        script:
          - mvn clean install
          - docker login test.domain.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
          - docker build -t <username:image_name:tag> .
          - docker push <username:image_name:tag>
        services:
          - docker